# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f11db2ef6485ff241a76a6ad34c60d42d9c45e67773de041eaf09227a29229888abe92ce8b8e1a84d373adc6ccaf10cf73e4718b0cb519f4f2f6d0ff8ee78d21

test:
  secret_key_base: d6d81db5e533b9c19bf258aac04b4abc59430d395d358f4d08cfac1f25cd325b940bc15660873fd83ece21135c2fe4aa91fa67ce7fe205c43b88097b484a5675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
